### ISSUE TITLE
Published Datasets miss the network diagram option

### ISSUE THREAD

**Issue by Jrulez** [alephdata/aleph#1083]
Since version 3.6.2 I miss the network-diagram option in published datasets. It has been there in previous versions.
When adding a network-diagram now, it's only possible to add network-diagrams to non-published datasets...

Can this feature be restored in the next release / fix?

**Comment by pudo** [comment]
I'd love to understand a bit more about how you're using this. Can you elaborate?

To clarify: this isn't broken at the moment, it's just not meant to happen. The way we're thinking about it, there are two sorts of data in Aleph: evidence and analytical material. Evidence is, for example, a companies registry or a document archive from a source. That stuff you can publish. But you can't alter it, i.e. a normal user cannot add new companies in an evidence dataset - that would defeat the point of having it as evidence. Making a network diagram is definitely altering the data, it's adding and changing entities.

Then there's analytical stuff, where people record their own work. There, anything goes -- you can make up ties, entities, draw a diagram that shows the devil is owning the pope. You can upload fake documents. We just don't people who do this to be able to make their information part of the public pool - to publish it. That's why at the moment you cannot really make a personal dataset public, and hence no public network diagrams. 

To be clear: we're thinking about how to make a workflow for publishing network diagrams, but not via the personal datasets. 

I'm not saying this is the way this all has to be, but that's how we're thinking about it at the moment. Maybe you can explain how your use case is different so we can find a solution.

**Comment by Jrulez** [comment]
Pudo,

I have a non-public Aleph instance used for investigating P2P fraud in the Baltics.
The bulk is not publicly accessible, only for a select group of people (lawyers, police-team, investigators etc).
Permissions are given on a per user basis, or for the very limited public part read to all visitors.
A group based permission-system would be great, but I understand that you also have your priorities.

We have several types of data-sets; evidence and analytical as you envisioned.
I use the network-diagram option to map out networks of people, contracts, companies etc. (FTM data-model) to create FTM entries.
Before the current version in use (3.6.2) I could create the diagrams also in the published data-sets, but this is not possible anymore.

The publish / not-publish difference is probably what I have missed, but still...
Most of my data-sets are personal data-sets, and also there the diagram-option has vanished. The diagrams still exist, but I can only find them via the Aleph homepage / workplace. There is also no possibility to create or import a diagram to these personal data-sets except for the Personal that still have the 'publish' option / are not published yet.

I now understand that I probably should not have used the 'publish' option for these data-sets.
Is there a way to un-publish a data-set? Couldn't find such an option on the aleph cmd line...

**Comment by pudo** [comment]
Just to be clear: there's a complete support for groups in the software, it just does not have a UI for creating groups (we manage groups in a different software). You could also make groups via SQL. 

The other thing - diagrams not shown in personal datasets - is probably a bug, I'll have a look tomorrow.

**Comment by Jrulez** [comment]
I read something about the group support, but couldn't find any ref on it in the API. 
Is there any (limited) documentation on it? If not, will have to fiddle around in SQL to find how it should work.

Pls Keep me posted on the diagram-bug, it probably has to do with the fact that these datasets were published. Looking forward to a fix or workaround (un-publish).

**Comment by kjacks** [comment]
@pudo the check here is currently if collection.casefile - should it be collection.writeable?

**Comment by pudo** [comment]
Ok, I've done a bit of documenting of where we are with groups. Is there any remaining action on this ticket?
