### ISSUE TITLE
Missing translations with Arabic translation

### ISSUE THREAD

**Issue by markjohnnightingale** [alephdata/aleph#1492]
Hello, there are a few missing translations when using Aleph in Arabic: 

- In the "Personal" dropdown:  Exports, Lists and System Status
- The 'About' button and the entire About text
- If the About text isn't to be translated, fix the LTR / RTL issues (specifically with the question mark)
- The Search button and the 'Advanced search' box appears in English
- Numbers appear in the non-english 'European' way with a . separating the thousands (in Arabic convention I believe this should be a comma?). This also needs fixing to a ',' in English locale as well – maybe need to fix the numeral locales so they format numbers across the board in accordance with the current locale ;)

**Comment by pudo** [comment]
Unfortunately, we'll need to wait until our Arabic partners provide the updated translations. This is except for the last point: we're running the Aleph UI in Moroccan Arabic, because our partners requested that we use latin numerals in combination with Arabic text - hence the somewhat French-ish number formatting :)

**Comment by pudo** [comment]
Ok they're actively on it :)

**Comment by pudo** [comment]
Closing this as it's going to be true to some extent for all eternity. We may want to use money in the future to do full localisation for point releases.
