### ISSUE TITLE
Orphaned entity mappings in UI

### ISSUE THREAD

**Issue by ltrgoddard** [alephdata/aleph#1722]
![Screenshot 2021-04-08 at 11 03 29](https://user-images.githubusercontent.com/1727065/114008428-20d15380-985a-11eb-8a72-4242d7db743e.png)

When using the (excellent) entity mapping UI, it's possible to create an entity mapping then delete the source table/document to which it refers, leaving an 'orphaned' mapping that can't be edited (see the third mapping listed in the above screenshot). Mappings are of course deletable from their own pages, but it's not possible to reach the relevant page via the UI when the source document has been removed.

**Comment by pudo** [comment]
So this is a bit of an icky issue to debug, because we don't want to just delete any mapping where the associated table is not available automatically. The table could be absent transiently, e.g. while the collection is being re-indexed or re-ingested. As a sort of compromise, I've now added a cleanup function to the `aleph update` command, which can be run to do some garbage collection. It's not an ideal solution, but the other options just all seem pretty risky in terms of accidentally deleting mappings that were still in use.

**Comment by ltrgoddard** [comment]
That sounds like a good compromise—thanks @pudo!
