### ISSUE TITLE
Improve dataset search

### ISSUE THREAD

**Issue by brrttwrks** [alephdata/aleph#2109]
Currently, when you search for Syria, datasets with the keyword Syrian don't get returned. We should make searches a bit more fuzzy in this regard. Not sure how inclusive the search is, but it should take into account the metadata (summary, sources) as well.

**Comment by Rosencrantz** [comment]
More comment, for a bit more context:

Finding datasets is crucial to our work. The expectation is that when type in keywords like 'owner' we'll get back datasets that have in the title or summary 'owner' but also 'owners'. Finding datasets currently is more about understanding how the dataset search fails so we can account for that failure by explicitly including additional search keywords. For example:

'owner' OR 'owners'

or

'Georgia' OR 'Georgian'

By not expanding partial keywords to include variations like this ensures we only get back the subset we are looking for. Imagine how many people simple do not find the dataset they are interested in because they type in a search keyword and don't get it back because they don't know how the search is failing them.

**Comment by tillprochaska** [comment]
Played around with this for a bit today, and was able to get good results for most of the use cases mentioned above using a simple fuzzy `multi_match` query (instead of a `query_string` query we use atm).

It’s a rather small change and doesn’t require changing index settings (i.e. doesn’t require recreation of the collections index in ES).

<img width="705" alt="Screen Shot 2023-02-15 at 13 48 37" src="https://user-images.githubusercontent.com/1512805/219031543-633fc384-8db5-4a85-80e6-f99310cb7547.png">

The downside of this is that power users loose the ability to use advanced search syntax, e.g. phrase search, wildcards, etc.

**Comment by tillprochaska** [comment]
@brrttwrks @jlstro What do you think about this trade-off? Do people rely on advanced search syntax for dataset/investigations search?

> The downside of this is that power users loose the ability to use advanced search syntax, e.g. phrase search, wildcards, etc.

**Comment by tillprochaska** [comment]
@brrttwrks @jlstro I have opened a PR that makes the collection search fuzzy by default. It’s a simple solution that doesn’t require re-indexing, but it is not perfect.

Below are a few examples of cases that the collection search will (not) be able to handle automatically once the PR is released.

Do you think this is good enough for the moment?

| Variant A | Variant B | Match? |
| --- | --- | --- |
| Romania | Romanian | ✅ |
| Leaked | Leaks | ✅ |
| Owner | Owners | ✅ |
| Malta | Maltese | ❌ |
| Companies | Company | ❌ |
| OpenContracting | Open | ❌ |

**Comment by jlstro** [comment]
Yeah sounds good. Why would leaked/leaks match but company/companies won't?

**Comment by tillprochaska** [comment]
> Why would leaked/leaks match but company/companies won't?

leaked/leaks has an edit distance of 2: To get from leaked to leaks, remove the d, and replace the e with an s.

company/companies has an edit distance of 3: To get from company to companies, replace the y with an i, and append e and s. 

This change will only cover cases with an edit distance of at max 2 (and this is a hard upper limit imposed by Elasticsearch).

**Comment by jlstro** [comment]
I see. Will "asdfg" and "xyzasdfgxyz" match?

**Comment by tillprochaska** [comment]
> I see. Will "asdfg" and "xyzasdfgxyz" match?

No, similar to OpenContracting/Open, this is not supported, because we can’t match partial keywords/prefixes.

While ES does support prefix searches, it cannot be combined with fuzzy searches. :/

**Comment by tillprochaska** [comment]
I think mid/long-term, we should still change how we index collection metadata to resolve some of the cases we cannot solve with fuzziness alone. I will add this to the endless list of ES related tasks/ideas.

**Comment by tillprochaska** [comment]
> Can we still use wildcards? Open*/OpenContracting matches?

No, as mentioned above, that is unfortunately the main limitation of this approach, the query syntax you’re used to isn’t supported in collection search anymore.

But let me double check whether there might be an option to still support at least prefix search (i.e. "open" matches "OpenContracting") and fuzziness at the same time somehow.

**Comment by tillprochaska** [comment]
@brrttwrks @jlstro Thanks for the feedback. I actually just thought of a way to combine the old behavior (which allows you to use wildcards like `Open*`) and the new behavior (which is fuzzy by default) which I had not considered before. I’ll update the PR and add a few more examples of queries that would (not) match with the updated behavior.

**Comment by tillprochaska** [comment]
> Is it possible to just re-index all the collection metadata without re-indexing the entire collection?

In theory, I think it should be much easier, the collections index is just a few MBs in size. But it would still require that we write new code to handle a zero-downtime index migration. Or at least automate the process of deleting and re-creating the collections index, then re-indexing the metadata. And even if that whole process is very fast, we might run into problems due to the collections index not being available, even if it’s just a very short time.

And it would definitely require more testing and benchmarking to ensure we get the new configuration right the first time.

So definitely more risk and effort compared to changing how we query (vs how we index).

**Comment by tillprochaska** [comment]
@brrttwrks @jlstro Ok, made a change that combines the previous behavior (with full support for the query syntax, including wildcards) and default fuzziness:

| Collection Name | Query | Match? | Notes |
| --- | --- | --- | --- |
| Romania | Romanian | ✅ | Edit distance == 1 |
| Leaked | Leaks | ✅ | Edit distance == 2 |
| Owner | Owners | ✅ | Edit distance == 1 |
| Malta | Maltese | ❌ | Edit distance == 3 |
| Companies | Company | ❌ | Edit distance == 3 |
| OpenContracting | open | ❌ | Doesn’t match partial keywords/prefixes by default |
| OpenContracting | open* | ✅ | Advanced query syntax is supported |
| OpenContracting | *contracting | ✅ | Advanced query syntax is supported |
| Jose Maria da Silva | "Jose da Silva" | ✅ | Could be considered a false positive, because the intent was to match only collections that contain "Jose da Silva" in that order. |

This works by basically executing two separate queries, then combining the results:

1. A query that supports the advanced query syntax (e.g. wildcards), but doesn’t use fuzzy matching by default (this is what we currently have).
2. A query that does not support the advanced query syntax, but uses fuzzy matching by default, without specifying it explicitly.

This explains the false positive (last example), while it wouldn’t be matched by the first query (because it uses quotes around the search keywords), it is matched by the second query. I think this has some potential for confusion, but maybe that’s acceptable?

**Comment by tillprochaska** [comment]
@jlstro Yes, that’s good feedback. We actually use an adaptive limit, but I think I didn’t mention that before.

* 0-2 chars: must match exactly
* 3 chars: one edit allowed
* >3 chars: two edits allowed

That should make sure that if for example you have a collection named "UK plane register", it matches the query "UK plane registry", but not "US plane register".
