### ISSUE TITLE
BUG: Some PDF documents are unable to be previewed in Aleph

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#2800]
**Describe the bug**

**To Reproduce**
1. Login to Aleph
2. Access the following url: https://aleph.occrp.org/entities/f271174901672dc457170005d38a23a17f183b3c.6c83687bda29dcc16c3dcfe96bbaf4c6065985c8
3. Observe the error message
4. Download and open the file

**Expected behavior**
Previewing the file should render it

**Aleph version**
3.13.0-rc1

**Screenshots**

**Additional context**

**Comment by tillprochaska** [comment]
@Rosencrantz The linked entity is a `Document` entity. When you ingest a PDF file, you should end up with a `Pages` entity as well as multiple `Page` entities for every page in the document.

I’m not sure when this document was ingested/uploaded, but if it’s been ingested some time ago, maybe Aleph used a different schema back then and the entities were not properly migrated or it wasn’t possible to migrate them?

If the document was uploaded recently, we should investigate how it was ingested to find out why a `Document` entity was created instead of a `Pages` entity.

**Comment by brrttwrks** [comment]
@Rosencrantz This was the dataset for which we re-ingested the documents after they were no longer available. The documents were empty after a crawl. But we re-ingested the documents from a store on kuciak. This solved the documents problem, but I guess there remain empty file entities.

**Comment by tillprochaska** [comment]
> Confusing. I see something a bit different. For a start this file is in the dataset twice. Once as a "file" and the second time as a "document". When I try to preview the file I get an error:

Just to clarify, the naming of multiple schemata in FtM is slightly confusing (probably for historical reasons). Every schema has a name and a label. The name is used to refer to the schema in source code, databases etc. The label is used to refer to the schema in the UI.

| Name | Label | Docs Link |
| - | - | - |
| Pages | Document | [Docs](https://alephdata.github.io/followthemoney/explorer/schemata/Pages/) |
| Document | File | [Docs](https://alephdata.github.io/followthemoney/explorer/schemata/Document/) |

So what we see is actually both correct - it’s just that I used the schema name and you used the schema label… :)

**Comment by stchris** [comment]
@Rosencrantz this issue can't be reproduced by uploading the document on the latest Aleph version, so most likely the best way forward here is to delete and re-upload the document, unfortunately.

**Comment by tillprochaska** [comment]
Can we close this?
