### ISSUE TITLE
BUG:  Network Error when scrolling documents 

### ISSUE THREAD

**Issue by scallop9845** [alephdata/aleph#2818]
**Describe the bug**
We use Aleph on a local network. When on the local network, in an investigation when looking at documents we get a network error after doing one scroll of the mouse or a couple page down keys or a couple of clicks on the scroll bar.  This happens in every investigation. This does not happen on the machine we have put Aleph on though. I can scroll without an error.

This also happens when I do a search. When I scroll the search results I get the same network error screen. I only have this issue with the two computers on the local network and not on the actual machine Aleph is on.

**To Reproduce**
1. Go to investigations
2. Click on an investigation
3. Click on Documents
4. Scroll down 
5. See error

1. type in a search
2. scroll the results 
3. see error

**Expected behavior**
I expect to see the documents or my results, not an error screen

**Aleph version**
3.13.0

**Screenshots**
![Capture](https://user-images.githubusercontent.com/122934133/213010609-cb443585-a1aa-4d86-936f-a82c2302a85b.PNG)

**Additional context**

**Comment by tillprochaska** [comment]
Hi @scallop9845! 
Thanks for reporting this issue. Unfortunately, I haven’t been able to reproduce the issue. Could you please provide the following additional details:

* A copy of any error messages in the JavaScript console of your browser. (Open Firefox Developer Tools, switch to Console tab, right click, select "Copy all messages")

**Comment by scallop9845** [comment]
Hi @tillprochaska,  the error message is below

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/api/2/entities?offset=30&limit=30&filter%3Aschemata=Thing&highlight=true&q=name. (Reason: CORS request did not succeed). Status code: (null).
Uncaught (in promise) 
Object { message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest, response: XMLHttpRequest, stack: "" }

**Comment by scallop9845** [comment]
Just wondering if anyone has any insight on this? I am still have an issue with this.

**Comment by tillprochaska** [comment]
Hi @scallop9845, sorry, I wasn’t able to reproduce your issue and it is related to the specific setup you use to deploy/run Aleph. Unfortunately, we’re unable to provide support for problems like this on GitHub.

You can check out our [support policy](https://github.com/alephdata/aleph/blob/main/SUPPORT.md), and if you qualify we may be able to provide limited support in our Slack community.

If you want to debug this issue yourself, I’d recommend you take a look at the network requests that are failing and make sure that they go to the expected host/port and that the API endpoint uses correct CORS headers. If you find a solution to your problem, we’d appreciate if you could post a short update here in order to help others experiencing the same issues.

I’m going to close this issue for now. Feel free to reopen it if you have additional information that suggests that this is indeed a bug.

**Comment by wsander** [comment]
@scallop9845 

Reproduced issue. If ALEPH_UI_URL does not include correct port, then OPTIONS request fails. Make sure ALEPH_UI_URL includes port number! Example of error:

![image](https://github.com/user-attachments/assets/8eb67b7a-8ac8-4219-94b6-46db6974ab52)
