### ISSUE TITLE
BUG: notifications load crashes UI in Safari

### ISSUE THREAD

**Issue by ozhyrenkov** [alephdata/aleph#2870]
**Describe the bug**
I’ve set up fresh installation of Aleph and getting /notifications page errors in Safari.
It appears every time one trying to access Aleph in Safari - it forwards to $URL/notifications and then UI crashes. In chrome works fine, no errors present in console.

**To Reproduce**
1. Install fresh Aleph
2. Open URL in Safari.
3. Log in.

**Expected behaviour**
Not fail in Safari, please :)

**Aleph version**
3.12.6

**Screenshots**
![image](https://user-images.githubusercontent.com/30832963/216769960-0ec14908-8f95-4c97-a94b-b1ad9e783bc3.png)
<img width="732" alt="image" src="https://user-images.githubusercontent.com/30832963/216770117-49f3e14d-85eb-4bfc-99d2-070576dc2941.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/30832963/216770229-adcb1592-8d4c-4bdd-86da-0686175e9621.png">

**Comment by tillprochaska** [comment]
Hi @ozhyrenkov, thanks for reporting this bug!

I can see that you’re running Aleph 3.12.6. This issue was fixed in https://github.com/alephdata/aleph/commit/8d7a4b1c072c395ba36682150adf30dae80f4183 which was released in 3.12.7. 

Please reopen this issue if you are still experiencing the issue after upgrading to 3.12.7 or later.
