### ISSUE TITLE
FEATURE: adding logging to POST to convert-document container

### ISSUE THREAD

**Issue by brassy-endomorph** [alephdata/aleph#2880]
**Is your feature request related to a problem? Please describe.**

I get constant 503's in my logs when POSTing to the convert-document container

```
10.0.44.8 - - [10/Feb/2023:17:16:00 +0000] "POST /convert?timeout=7200 HTTP/1.1" 503 4 "-" "python-requests/2.28.1"
```
I would like log messages telling me what went wrong so I can debug it

**Describe the solution you'd like**

Any logs. Any at all.

**Describe alternatives you've considered**

Divination

**Comment by stchris** [comment]
Thanks, this is in itself a valid concern. The reason you are seeing 503s on the convert-document container is that it is probably busy doing something (which it should be). There's a relatively weird locking mechanism in place which also allows us to scale up when this happens (because there's one libreoffice process per container and it is potentially long-running). See here:

https://github.com/alephdata/ingest-file/blob/379effdd76006d316f9f73150728992bb09f7246/convert/convert/app.py#L27-L28

Good news though: in `ingest-file` versions `3.18.0` (and newer) `convert-document` as a separate container and service is gone, as it has been integrated into ingest-file. This change will be rolled out soon with the new Aleph version `3.13.1` (which we are testing internally at the moment).
