### ISSUE TITLE
Add "create alert" button to search results.

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#320]
As a user, I want to be able to receive notifications about future documents matching a term when conducting a search by clicking a button to create a standing alert.

**Comment by pudo** [comment]
Any further work needed on this, @emmina & @iaincollins ?

**Comment by emmina** [comment]
I think it's done.

**Comment by iaincollins** [comment]
I think it's broadly okay - although, it's not an ideal experience when the site is slow, though it does track if an action is in progress to try and keep it's state from getting messed up from repeated clicks.

1. Some feedback from Dan was that maybe we only want to run the check to see if you have an alert *after* you submit a search (and so it would make sense to hide the button until then) as a user that made more sense to him. If we did that, it would also reduce the amount of effort required client side.

2. We could also, optionally, turn off the toast alerts if we feel they are too much in this context?

Let me know if we we think we should do either of those, otherwise vote to close.

**Comment by iaincollins** [comment]
Okies, will change the behaviour and address the issue with turning them off when things are running slower (#367).

**Comment by pudo** [comment]
Ok, closing if the only remaining task has its own issue.
