### ISSUE TITLE
BUG: Searching within a document can return a lot of results, but only the first page is shown

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#3320]
**Describe the bug**
When searching a large document in a dataset which has a significant number of results, only the first set of results are show, there is no progressive loading of results and no pagination available.

**To Reproduce**
1. Go to a large document with lots of text and lots of pages
2. search in the document (box on right of screen) for a very common word that will generate > 50 results
3. Scroll down the list of results
4. See error. Not all results are shown and there is no way to see expanded set of results

**Expected behavior**
You should be able to scroll or paginate through all results

**Comment by YveSalazar** [comment]
Hi! I'm having the same issue here. What the issue could be? 

**Describe the bug**
Only 30/10000 results are shown on the dashboard (limit=30) and then when it's time for offset, the request is made to localhost. 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to a large dataset with 10,000 results
2. Scroll down the list of results until 30 results are shown
3. See Failed Network error on screen / See http://localhost:8080 request on dev tools

**Expected behavior**
You should be able to scroll or paginate through all results
