### ISSUE TITLE
How can I get highlighting/snippets in search results in the API?

### ISSUE THREAD

**Issue by jbothma** [alephdata/aleph#355]
https://github.com/alephdata/aleph/wiki/API#searching says 

> Results will include documents and entities, and their metadata, record snippets (for highlighting)

But I can't find them in the results, and I can't figure out if I'm supposed to provide a query string value to show them.

Are they currently disabled/broken? It sounds like you're figuring out how to add them on the UI side back.https://github.com/alephdata/aleph/issues/340

**Comment by pudo** [comment]
So Aleph used to run two sets of queries for every search: one against the set of documents indexed in the application, and a second against every page in the matching documents to find the highlights. This is so that it could point you to a specific page, rather than say: somewhere in this document there is a match. The downside was performance: if your search yielded 30 results, you'd in pratice be running 31 index queries.

So for the moment this is uncoupled, and you'll get highlights by calling /api/2/documents/id/results?q=term?highlight=true for a particular result doc. The plan is to integrate this into the result preview rather than the results overview.

**Comment by jbothma** [comment]
Awesome, thanks! cc @schalkventer
