### ISSUE TITLE
Mock up and implement notifications overview

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#391]
This screen should present a more styled presentation of the notifications of a particular user.  It may also be good to include alerts management on the same page, perhaps as a sidebar or as a tab. 

When the user is not logged in, it should show a permission denied error.

**Comment by uhhhuh** [comment]
![screenshot from 2018-04-11 15-50-40](https://user-images.githubusercontent.com/27774810/38621001-321a47fe-3da0-11e8-9ea2-19b975479910.png)

"Receive e-mail when there are new results." — Can we move this text from the textbox on the left of the "Add alert" button to somewhere beneath? Else users might interpret the purpose of the textbox as  a place to put their email addresses instead of search terms.

**Comment by pudo** [comment]
Things we discussed today: 

* We want a read/unread status for notifications, and a "mark all as read" button. Clicking a link in a notification should mark that notification read. 
* Need to figure out roll-up types: by event type? By alert? 
* We want the notification stream in case files and in the global scope to look the same
* Here's the [current list of possible notification types](https://github.com/alephdata/aleph/blob/master/aleph/model/event.py#L39).
