### ISSUE TITLE
Stand up a copy of Aleph on Kubernetes

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#418]
* Create a small cluster on DO
* Run Aleph, including database and search index
* Make volumes persistent
* ... 
* Profit!

**Comment by pudo** [comment]
WIP repo: https://github.com/sunu/aleph-kube

**Comment by Ueland** [comment]
@sunu I have some input regarding the k8s deployment files, should i lay it out here or as dedicated issues in the aleph-kube repo?

**Comment by pudo** [comment]
I think it'd be great to centralise issues around here, if only as the next best thing to documentation ;)

**Comment by sunu** [comment]
@Ueland The aleph-kube repo is mostly a throwaway experiment. So yeah having all the discussions here is definitely better.

**Comment by Ueland** [comment]
My points are with regards to stability and durability for the application as a whole:

- Does the different containers/apps handle that multiple instances are running? If not, those who do not should  be made to handle it (redundancy and such), allthough it might be worse for databases, that will be solved with the ability to use a central DB (For example Google Cloud SQL) Those apps who handle it should be scaled up in the deployments file to at least two containers. (replicas: 2)

- The current update strategy is to recreate, in order to ensure uptime when something is changed, the update should be of the rolling kind, this ensures that the app/service never goes down. Allthough that might be troublesome as the app does DB-migration and such automaticly? 
```xml
strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
```

- For the containers that can run in multiple replicas, podAntiAffinity should also be set so that one does not get two of the same containers on the same cluster node.

- livenessProbe and readinessProbe should be defined so that k8s knows when a container is up, or simply sick. You can define either a cmd to run, or a HTTP URL to check.

- Both resources limits and requests should be defined for each container in each deployment. If its not  defined, uncool side effects will appear when the app starts getting load. I prefer that limits and requests are the same, so the cluster dosn't start to move containers around when everything is up and running.

That should be enough for now ;)

This is based on the systems i already administer in K8s clusters, i am also going to set up our instance of Aleph on k8s.

**Comment by pudo** [comment]
Ok. So we have aleph running on k8s pretty stable now, but I'm not entirely sure how to best share the object specs without duplicating and having it run out of data super-fast. 

Anyway, the original ticket is done.
