### ISSUE TITLE
Entity Disambiguation

### ISSUE THREAD

**Issue by jcshea** [alephdata/aleph#436]
Core idea : we can learn entity properties from the aleph corpus.  Including: 

Extracted entity disambiguation / linking.   
- Starting with the greater POI set, generate a tag-co-occurence extract for each POI proper name (SQL on Aleph prod for the same drafted).  Run de-dupe (or similar) on these tags and accept the tags clustered around the POI proper name as aliases of the POI.
- Assuming the tag-frequencies from the co-occurence extract represent the true 'context' for the named POI, construct a document-level classifier, weighted by a chosen metric (co-occurence frequency or the like) to classify POI-clustered tags in a given document (ie teach a model that when Putin shows up with Sechin, it's quite likely to be VVP).  This is similar to what most entity disambiguation methods do, but trained on our own corpus.
- Longer term : augment with wikidata entities; research the NEL library or similar to leverage open data (https://github.com/wikilinks/nel) for a similar task

**Comment by jcshea** [comment]
I've been thinking about the entity-duplication problem Pudo and I spoke about - ie what to do when you (inevitably) have multiple Vladimir Putin (The Putie, as I like to think of them).  Certainly, even within a constrained list of subjects, such as our POI's, you'll encounter multitudes of Putie.  In literature, this problem is known as 'coreference resolution'.

After a bit of research, lo and behold, a champion emerges!  I was converging on a clustering-based approach to the issue, in the hope that distinct Putie would cluster themselves around distinguishable tag-sets, and therefore the 'true identity of any given Putin would be inferrable from the associated tags, at document level or at worst at collection level.  After some digging, turns out there's a solution already built!
https://github.com/huggingface/neuralcoref

This is effectively a spacy implementation of the coreference resolution technique adopted by the StanfordNLP library, but with user-specified retraining on bespoke corpora and spacy's inherant multi-lingual support at the fore.  Worth a spin, methinks.

**Comment by pudo** [comment]
Nice research; especially NEL looks like something that's surprisingly close to the discussions we had in Sarajevo.

However, I think we need to turn this discussion on it's a head a bit to make sure we're going places: what are the specific types of user-facing system behaviour that we want to enable by doing this. There's no point in us doing a lot of clustering if we don't have a clear idea of what specific user problem we're trying to solve, and how we intend to design the user-facing parts of the system to solve it. 

So let's plot this out here first. I'm being insistent on this here because "entity disambiguation" is pretty much the core definition of investigative reporting, so we need to be precise in how we *enable users to do it* (and not presume that we can somehow *solve it for them*).
