### ISSUE TITLE
Refactor view management in the app

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#453]
We're working to come up with a way to simplify the navigation of the app -- too many screens have too many buttons at the moment. Here's a mockup of what it would look like if we had an additional design element, a sidebar that would contain the different available view for each pane: 

![sidetabsconcept-document](https://user-images.githubusercontent.com/41628/43269074-6591fe06-90f2-11e8-845a-e1f3b87b6c20.png)

![sidetabsconcept-docview](https://user-images.githubusercontent.com/41628/43269083-6b956cf2-90f2-11e8-9822-c5636bf05fc9.png)

**Comment by emmina** [comment]
### PREVIEW
- For the preview there should be 3 types of sidebars which contain:

1. show document, show text, download, show details (for documents and images)
2. show document, download, show details ( for other files that are not entities)
3. settings, access (for sources)

- For this type of viewing document, buttons that should stay on the top of the preview should be: OPEN, SEARCH and OPEN AS FOLDER.
- Sidebars should also contain 'Source' and 'Connections', so for Entities these should be only options on the sidebar.

### DOCUMENT VIEWER
- When it comes to opening documents, so when we are on the page that is only for that one document, there is only one type of sidebar and it is on the Document viewer and Image viewer. It should contain: 'View' and 'Text'.
- On other types of files, that are not entities, on the Preview side of viewer should be a button 'Download', and button 'Up' should be removed, because we are adding breadcrumbs on the front side of the page.
- It stays here also that on the right side of the page, where is Preview of the document, it should have sidebar that contains: 'Source' and 'Connections'.

**Comment by emmina** [comment]
### Button sidebar in code
- For the sidebar that should be shown on the Preview, I would add it in _Preview.jsx_ component. This sidebar will only be shown on preview of the document, but when you open a page of the same document, you lose preview and get InfoPane component. So we need to put the button sidebar on that component also, more exactly on _DocumentInfo.jsx_.

- When it comes to opening the page of the document, sidebar should be put on _DocumentContent.jsx_ and only if it is PDF or Image.

**Comment by pudo** [comment]
Ok, I need to clarify this for my brain, too. We have the following cases:

* Collections
  * Actions: Settings, Access Control, Run XRef, Search
  * Views: Browse as leak, view Xref, Contents
* Entities
  * Actions: Open, 
  * Views: Details, Source, Connections, Similar
* Documents
   * Actions: Open, Download, Paginate (prev, next), Delete
   * Views: Preview, Metadata, Connections, Raw text, ((Search)), Similar, Attachments

Is that correct? Missing anything?

**Comment by pudo** [comment]
Regarding structure: what if we had a setup like this, where we separate out the layout of the sidebar in general from the specific type of sidebar...

```jsx
sidebar = <DocumentSidebar document={document} preview={true} />;
return <Sidebar sidebar={sidebar}>{view}</Sidebar>;
```

But how does view come about?

**Comment by pudo** [comment]
Ok, new name agreed to be ``ViewsMenu``, i.e. ``DocumentViewsMenu``, ``CollectionViewsMenu``.

**Comment by emmina** [comment]
- [ ] fix toolbar on disabled buttons

- [ ] finalize disabled button and badges

- [ ] integrate Edin's icons

- [ ] truncate the collection name

- [ ] show full path for documents (breadcrumbs)

- [ ] put total count for tags, similar, xref,.. on breadcrumb

- [ ] check directorship tooltip

- [ ] check header on info pane for documents (clean up the DocumentViewer, pagination should be moved to PDFViewer and TextViewer, make it centered)

- [ ] list icons that are not in the follow the money (for Edin)

- [ ] for emails, move show attachments and other to sidebar

- [ ] add maximized info pane when clicked on tags, as it is on the similar
