### ISSUE TITLE
Admins does not get deleted

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#575]
Removing an admin from the Aleph config does not cause the user in question to get updated to is_admin=f in Postgres, perhaps something that should be done upon start of the API-container?

**Comment by pudo** [comment]
The admin flag is retained in the JWT for a day, and some permissions are cached to redis. So the effect is not going to be immediate if we write directly to the DB. The cache issue can be fixed with ``aleph repair``, but for the JWT we don't have revocation mechanism. Do you know of any best practices regarding this?

**Comment by pudo** [comment]
I don't quite know how to deal with this: there are two possible origins for `admin` flags: OAuth and the config file/env. It's unclear to me how we could disable admin based on the env without overwriting the OAuth-supplied admin flags...

**Comment by pudo** [comment]
This has been open for a while but I really have no idea how to not do this in a consistent way, so I'll leave it closed unless we have an actionable plan or a clear idea of what the desired behaviour is.
