### ISSUE TITLE
OCR'ed text pages displayed in the wrong order

### ISSUE THREAD

**Issue by moreymat** [alephdata/aleph#724]
I fed aleph some image PDFs that were OCR'ed fine, except the text pages appear ill-sorted (at least in the UI): 1, 10, 11, ... , 19, 2, 20, 21, ... , 29, 3, 30 etc .
I don't know if the problem is in the OCR process (pages concatenated in the wrong order) or just in the viewer.
@sunu said: "We are trying to sort on Page.index. But Page.index is being treated as a string rather than an integer. That’s why the weird order of pages. Will fix asap"

**Comment by pudo** [comment]
Looks like we can fix this bug without re-indexing, cf.: 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-sort

We just need to apply a cast for numeric and date-based data.

**Comment by sunu** [comment]
I fiddled with this a bit. Here's what I found out:
1. `numeric_type` casting during sort is only available in ES 7.3. We have to upgrade.
2. It should work for our date data. But it doesn't fix this particular issue because we have mapped page `index` as `keyword`. `numeric_type` casting needs the field to be mapped in as a numeric type.

So looks like we need to re-index or try something else?

**Comment by pudo** [comment]
The problem is that `followthemoney` doesn't strongly convert number types, i.e. it doesn't output ints. That's because a lot of our data keeps numeric values in odd formats (e.g. "$ 20,000,000.4434").

I guess the cleanest solution would be to make numeric subfields for each number property, i.e. `properties.index.num` which contains a best-effort numeric cast. That would probably require an index change, not sure it'd be necessarily a re-index.
