### ISSUE TITLE
File size limit?

### ISSUE THREAD

**Issue by kokoroko2** [alephdata/aleph#752]
What is the maximum file size supported? I have a 3gb .csv and I probably have to split it into several smaller files. But what is the size of these smaller files?

**Comment by sunu** [comment]
Hi @kokoroko2! In general we try not to load the entire content of a file into memory. So ingesting a 3GB csv file should be pretty much doable without any splitting. It will take some time to be processed though.
Can I ask if you have written a mapping for the said csv file or are you uploading it as is?

**Comment by kokoroko2** [comment]
Hello Sunu! As I am not extracting entities, I tried to ingest the file normally. 
I split into 50mb files to test. 
The content has been indexed because I can search for any word inside it and I find it. 
But I can't open the CSV through the interface (pic attached). 
Also, on the terminal came hundreds of lines written: 
WARNING: followthemoney.proxy: [indexText] too large. Rejecting additional values.

![csvbroken](https://user-images.githubusercontent.com/54646945/64554373-ae149500-d311-11e9-815f-23e4b9744ac0.png)

**Comment by pudo** [comment]
Hey Laura! I'm not sure why the tabular preview isn't showing, perhaps you can also send us your browsers console output -- there might be some weird transmission error when the UI starts loading the CSV.

But unfortunately, there's a second problem here: ElasticSearch can only really index 100MB of raw text per document. Since we add some metadata in Aleph, we're actually limiting the size of text from the document to 70MB, to leave enough padding for metadata. Such large documents also make Aleph less than useful: all it's going to tell you, really, is that somewhere in this very large file there is a mention of the word you're looking for...

I'd encourage you to have another look at the mapping process that @sunu mentioned -- it's a really nice way to generate semantical entities from structured data. We're drafting documentation for this here at the moment: https://docs.alephdata.org/developers/mappings 

On a related note, this tracker is mostly for bug reports and feature ideas. Questions like "what's the file size limit?" might receive a quicker response in our Slack instance. You can sign up for it here: http://slack.alephdata.org

**Comment by kokoroko2** [comment]
Oops, sorry. Very grateful! I just entered the Slack.
