### ISSUE TITLE
Aggregating in bulk

### ISSUE THREAD

**Issue by davidszakonyi** [alephdata/aleph#902]
Thanks for such great software. I see that balkhash is a great tool for writing entities that can't be stored in application memory, but what if the source file is not already an ftm mapped .ijson file?

I have a quite large csv that I'd like to push to our Aleph server, using its corresponding .yaml file. Is there a good way to use bulkhash in conjunction with the ftm aggregate command? Thanks!

**Comment by pudo** [comment]
Hiya @davidszakonyi :) I'm a little bit confused by your question, maybe you'll have to help me sort through it. In general let's assume you have a working environment with `followthemoney` and `balkhash` installed -- whether it's the Aleph server or your own workstation. 

Given that, you might run a process like this (where `foo` is your dataset name): 

```bash
cat foo.csv | ftm map-csv foo.yaml | balkhash write -d foo
balkhash iterate -d foo | alephclient write-entities -f foo
```

You can of course run this inside the Aleph server, but I'd suggest running it outside instead. If you do operate it inside aleph, the last command is `aleph write-entities` instead of `alephclient`. 

Here's some examples you might find useful: https://github.com/alephdata/aleph/blob/master/mappings/Makefile 

And of course the docs: https://docs.alephdata.org/developers/ftm#loading-data-from-a-local-csv-file

**Comment by pudo** [comment]
Hey, do you think we can close this error report?

**Comment by davidszakonyi** [comment]
Yes, this worked wonders. thanks!
