### ISSUE TITLE
Aleph Installation Howto

### ISSUE THREAD

**Issue by critocrito** [alephdata/aleph#965]
Hey,

I wrote an installation how-to for Aleph that avoids the use of Docker. It is based on version 3.4.4 and put together based on the Dockerfiles that Aleph is using. You can find the latest version [in this gist](https://gist.github.com/critocrito/c5afe9c82ba03ecb1cb76b2d50deb75f). Feel free to use it if you find it useful.

**Comment by pudo** [comment]
This is pretty glorious, thanks so much for taking the time to document and contribute your efforts. Would you be a) OK with us adding this to the documentation at https://docs.alephdata.org/ and b) would you mind me sending you an invite to that service so that you can edit it at your choice? 

I honestly wasn't 100% sure it could be done, but it's oddly comforting that it is :)

**Comment by critocrito** [comment]
Yes, you can add it to the documentation, and yes, I take that invite. 

It's not that complicated in the end and I think it would also not be that much work to turn Aleph into proper Debian packages. There are a few things that would make life easier though, e.g. spacy is not part of the `requirements.txt` file, or distribute the right version of `unoconv` with the `convert-document` service.

**Comment by pudo** [comment]
For what it's worth, I removed the dependency of `convert-document` on `unoconv` based on #957 yesterday, now it just requires the version of python-uno that ships with Ubuntu and Debian :)

**Comment by pudo** [comment]
I've imported this in the documentation here now: https://docs.alephdata.org/developers/look-ma-no-docker - feel free to edit.
