### ISSUE TITLE
Alerts based on a search ignore ""-operator

### ISSUE THREAD

**Issue by elias2011** [alephdata/aleph#996]
When you search for an entity you can specify your search terms using quotes to find only the documents containing the exact pattern of terms you want ("Barack Obama") and not Barack AND Obama. If you create an alert (#320) based on such a search (via the icon in the search mask), the resulting alerts list documents, that contain Barack AND Obama and not only the intended "Barack Obama". Depending on your actual search terms, this can lead to a lot of false-positives. If you check on your notification subscriptions, the search term will be displayed correctly as "Barack Obama". 

Desired behaviour would be, that alerts based on a search for an exact sequence of terms should only list documents containing that exact sequence of terms.

I couldn't yet verify, if the same behaviour applies to alerts created directly in the alerts section. I haven't tested whether this applies to the other options of specifying your search as well.

**Comment by pudo** [comment]
Thanks for reporting this behaviour. I'm a bit at a loss for how to debug this, since we're just calling a particular search method of ElasticSearch, which in turn handles the parsing and composition of the query: [query_string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html). 

I've changed the alerting code to make it so that it will be less primed to search matches in multiple fields, making it more defensive in a general sense. But I cannot really reproduce the bug you describe - when I create an alert for `"Some Name"` and upload a file with the string `Some Other Name`, no alert is generated. Can you check again, and possibly provide further detail?
